### ISSUE TITLE
Unknown ephemeris FTP site

### ISSUE THREAD

**Issue by AKHughes1994** [twillis449/ALBUS_ionosphere#26]
Hello, 

More of a question then a real issue, 

I've installed ALBUS through docker (the easy way I just downloaded the repo and installed it using the pre-included docker file) 

I get some errors when successfully running the South_Africa_experiment.py code (namely, `BrokenPipeError: [Errno 32] Broken pipe` and `FileNotFoundError: [Errno 2] No such file or directory: 'RX3name': 'RX3name'`) but these seem to have no effect, and the code runs well and outputs the TEC file. 

However, If I push the start and end times too close to the current date, I get the title error `Unknown ephemeris FTP site`, and the code crashes. I interpret this as the RINEX file doesn't exist on the trignet servers. Looking at the website http://www.trignet.co.za/, it says that the RINEX files are posted daily, but as of today (Feb 8 2024) the most recent file I can get is Jan 27 2024. 

So my question is, is this grace period standard? And is there any way to get around it?

Thanks for the help and the Dockerfile; it made it really easy to install. 
Andrew

**Comment by twillis449** [comment]
Basically this system runs at the will of all the GNSS support sites. So if something isn't provided there ...

How to obtain RX3name instructions are given in the INSTALL file at about line 85 - doesn't matter much for you as trignet files still use rinex2 file names.  However the SAAO in Sutherland is part of the global GNSS network and the system may be looking for the files it produces at some other non-trignet site.

The 'Unknown ephemeris ftp site' message is occurring because the system is looking for an SP3 ephemeris file from CODE (center for orbital determination europe) - odd that they are being so slow. Probably I should put in some code to have the software look for another site serving SP3 files if CODE is not producing it.

Trignet may claim to post files daily, but 'daily' usually means at least 3 or 4 days after the fact. But an 8 or 9 day delay seems a bit long.

This system is absolutely NOT a real time system and there's not much you can do about it at the present time.

**Comment by AKHughes1994** [comment]
Hi, 

Thanks for the fast reply, and I apologize in advance for what will likely be a very novice question. 

When you install Albus via Docker, do you happen to have a suggested approach for including the RX3Name and gfzrnx software? 

My current approach was to download the software (both are just single executables), rename the gfzrnx_[version info]  to gfzrnx, and place both fo them in the `bin` directory from the repo. The Dockerfile already has this line in it.

`ENV PATH "$ALBUSINSTALL/bin:$PATH"`

So I assumed the executables would be picked, but I am still getting the `FileNotFoundError: [Errno 2] No such file or directory: 'RX3name': 'RX3name'`

Admittedly, I am a super novice with docker, so I was wondering if you could advise me. Regardless, thanks for the help already.

**Comment by twillis449** [comment]
I've never used docker for anything. The docker interface was developed by my colleague Benjamin Hugo. So I hope he will respond to your questions.
As far as RX3name gfzmx issues - are you sure you made them executable after downloading them?

**Comment by AKHughes1994** [comment]
Hi Tony, 

It's definitely executable. If I put RX3Name in my local/bin (in my PATH) I can execute it via the name RX3Name, outputting, 

![image](https://github.com/twillis449/ALBUS_ionosphere/assets/49698839/6c935022-5717-4d1f-ab9b-04ee55140439)
